In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import haversine_distances
from math import radians, degrees
import time

In [2]:
# df contains the cleaned original catalog (1177 objects)
df = pd.read_csv("/mnt/c/Users/joerg/OneDrive/Dokumente/UNI/Bachelor of Science/Bachelorarbeit/Jupyter Notebook/blazar_clean.csv")
# df_centers contains the coordinates of the 19 neutrino hotspots obtained for L_min = 4.0
df_centers = pd.read_csv("/mnt/c/Users/joerg/OneDrive/Dokumente/UNI/Bachelor of Science/Bachelorarbeit/Jupyter Notebook/neutrino_hotspots_40.csv")

## First version of matching algorithm
Loops through all neutrino hotspots and finds blazars closer than r (in degrees) and prints the index of matched hotspots, as well as the coordinates of the corresponding blazars. Does not filter out duplicates yet. 

In [3]:
r = 0.55
t0 = time.time()
correlated = []
df_centers = df_centers.to_numpy()
catalog = np.array(df)
for i in range(df_centers.shape[0]):
    for j in range(catalog.shape[0]):
        if degrees(haversine_distances([[radians(_) for _ in [df_centers[i,2], df_centers[i,1]]], [radians(_) for _ in [catalog[j,4], catalog[j,3]]]])[0,1]) < r:
            correlated.append(np.array((catalog[j,3],catalog[j,4])))
            print(i)
t1 = time.time()
print(f"\n{len(correlated)} Matches were found")
print(f"\nIt took {t1-t0:.3f}s to run the matching algorithm")
correlated

1
3
4
5
6
10
11
12
13

9 Matches were found

It took 0.266s to run the matching algorithm


[array([300.850458, -32.862528]),
 array([59.430375, -7.854058]),
 array([ 59.890292, -26.258689]),
 array([ 25.792208, -32.015747]),
 array([340.7865  ,  -6.150719]),
 array([274.895792, -63.763389]),
 array([ 44.0535  , -21.624747]),
 array([346.222042, -36.416669]),
 array([ 97.747958, -24.112828])]

The matching algorithm is expected to return 10 matches for r=0.55 and L_min=4.0 (see Buson). 9 out of 10 matches can already be identified. The missing correlation is due to a small deviation in the neutrino hotspot clustering method for certain hotspots. Note the following difference in calculated distances:

In [4]:
# The angular distance between the missing hotspot and blazar pair according to applied clustering method.
degrees(haversine_distances([[radians(_) for _ in [df_centers[9,2], df_centers[9,1]]], [radians(_) for _ in [catalog[920,4], catalog[920,3]]]])[0,1])

0.5891424639750822

In [5]:
# The angular distance between the missing hotspot and blazar pair according to Buson.
degrees(haversine_distances([[radians(_) for _ in [-22.27, 309.38]], [radians(_) for _ in [-21.776858, 309.213208]]])[0,1])

0.5168138467295282